export const selectCarsList = (state) => state.cars.cars
export const selectFavoriteCars = (state) => state.cars.favoriteCars
export const selectFilteredList = (state) => state.cars.filteredCars
export const selectLocation = (state) => state.cars.location
export const selectModalStatus = (state) => state.cars.modalMenuStatus
export const selectSearchedId = (state) => state.cars.modalId
export const selectPage = (state) => state.cars.page
export const selectLimit = (state) => state.cars.limit
export const selectIsLoading = (state) => state.cars.isLoading
export const selectIsLoadingForm = (state) => state.cars.isLoadingSearchForm
export const selectReachOut = (state) => state.cars.reachOut
